ASSET_TYPE_SUBDOMAIN = "subdomain"
ASSET_TYPE_IP = "ip"
ASSET_TYPE_CERT = "certificate"
ASSET_ENVIRONMENT_EXTERNAL = "external"
ASSET_ENVIRONMENT_INTERNAL = "internal"
DISCOVERY_MODULE = "discovery"
RECON_MODULE = "recon"
SCAN_MODULE = "scan"
ASSET_TYPE_TLD = 'TLD'
ASSET_TYPE_THIRD_PARTY = "third_party_integration"

GET_METHOD = "GET"
POST_METHOD = "POST"

DNS_TWISTER_FUZZER_ORIGINAL  = "*original"

HIGH_SEVERITY = "HIGH"

FINDING_TYPE_PHISHING = "phishing"
