---
# tasks file for native-setup
- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Add deadsnakes PPA for Python 3.9
  apt_repository:
    repo: ppa:deadsnakes/ppa

- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gcc
      - git
      - gnupg
      - libpcap-dev
      - dnsutils
      - python3.9
      - python3.9-dev
      - python3-pip
      - python3-setuptools
      - python3-requests
      - unzip
      - software-properties-common
      - wget
    state: latest
    update_cache: true

- name: Add ~/.local/bin to PATH in ~/.bashrc
  lineinfile:
    path: ~/.bashrc
    line: "export PATH='$HOME/.local/bin:$PATH'"
    create: yes
    state: present

- name: Reload ~/.bashrc
  shell: source ~/.bashrc
  args:
    executable: /bin/bash

- include_tasks: install-tools.yml

- name: Install pip dependencies
  pip:
    name:
      - "dnspython<=2.0.0"
      - "dnstwist[full]"
      - ipwhois
      - wafw00f
      - "git+https://github.com/cisagov/findcdn.git"

- name: Download requirements
  get_url:
    url: https://raw.githubusercontent.com/PhonePe/mantis/refs/heads/main/requirements.txt
    dest: /tmp/mantis-requirements.txt

- name: Install Python dependencies
  pip:
    requirements: /tmp/mantis-requirements.txt
